import mne

print("Loading Motor Imagery data (Run 4)...")
# 1. Load Run 4: Imagined movement of left vs right fist
subject = 1
runs = [4] 
file_paths = mne.datasets.eegbci.load_data(subject, runs)
raw = mne.io.read_raw_edf(file_paths[0], preload=True)
mne.datasets.eegbci.standardize(raw)

# Apply standard noise filter
raw.filter(l_freq=1.0, h_freq=40.0)

print("Extracting stimulus events...")
# 2. Extract Events from the raw file's annotations
events, event_dict = mne.events_from_annotations(raw)

print(f"Events found: {len(events)}")
print(f"Event mappings: {event_dict}")

# FIX: Map the colors to the integer IDs generated by MNE
# 1 (T0) = Rest, 2 (T1) = Imagine Left Fist, 3 (T2) = Imagine Right Fist
color_mapping = {1: 'green', 2: 'blue', 3: 'red'}

print("Opening interactive plot...")
# 3. Plot the raw data with the events overlaid
raw.plot(
    events=events,
    event_color=color_mapping,
    duration=15.0, 
    n_channels=20,
    title="PhysioNet S001 Run 4 - Motor Imagery with Events",
    block=True
)